---
title: "Project 2"
author: "Cassandra Chou"
date: "2024-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1
### part a)
```{r part 1a}
library(tidyverse)
library(tidytuesdayR)

Exp <- function(x, k) {
  exp_val <- 1
  for (i in 1:k) {
    exp_val <- exp_val + x^i/factorial(i)
  }
  exp_val
}

Exp(3, 2)

```
### part b)
```{r part 1b}
sample_mean <- function(x) {
  n <- length(x)
  mean_val <- 0
  for (i in 1:n) {
    mean_val <- mean_val + x[i]
  }
  
  mean_val/n
}

sample_sd <- function(x) {
  n <- length(x)
  sd_val <- 0
  mean_x <- sample_mean(x)
  
  for (i in 1:n) {
    sd_val <- sd_val + (x[i] - mean_x)^2
  }
  
  sd_val <- 1/(n-1) * sd_val
  sqrt(sd_val)
}

sample_mean(c(1, 2, 3, 4, 5))
sample_sd(c(1, 2, 3, 4, 5))

```


### part c)
```{r part1c}
calculate_CI <- function(x, conf = 0.95) {
  alpha <- 1 - conf
  degrees_freedom <- length(x) - 1
  t_score <- qt(p = alpha / 2, df = degrees_freedom, lower.tail = FALSE)
  
  mean_x <- mean(x)
  se_x <- sd(x)/sqrt(length(x))
  lower_bound <- mean(x) - t_score*se_x
  upper_bound <- mean(x) + t_score*se_x
  
  c(lower_bound, upper_bound)
}

# Test
x <- c(1:100)
dat <- data.frame(x = x)
fit <- lm(x ~ 1, dat)

# Calculate a 95% confidence interval
confint(fit, level = 0.95)

calculate_CI(x)

```

## Part 2
```{r part2 setup}
library(here)
if (!file.exists(here("data", "tuesdata_rainfall.RDS"))) {
    tuesdata <- tidytuesdayR::tt_load("2020-01-07")
    rainfall <- tuesdata$rainfall
    temperature <- tuesdata$temperature

    # save the files to RDS objects
    saveRDS(tuesdata$rainfall, file = here("data", "tuesdata_rainfall.RDS"))
    saveRDS(tuesdata$temperature, file = here("data", "tuesdata_temperature.RDS"))
}

rainfall <- readRDS(here("data", "tuesdata_rainfall.RDS"))
temperature <- readRDS(here("data", "tuesdata_temperature.RDS"))

library(tidyverse)
library(dplyr)

glimpse(rainfall)
glimpse(temperature)

```

```{r part2}
df <- rainfall %>% drop_na() %>% mutate(date = ymd(paste(year, month, day, sep = "-"))) %>% select(-month, -day)
df$city_name <- str_to_upper(df$city_name)

df <- inner_join(df, temperature, by = c("city_name",  "date"), relationship =
  "many-to-many")

glimpse(df)

```

## Part 3
### part a)
```{r part 3a}
library(ggplot2)

ggplot(data = df %>% filter(year >= 2014), aes(x = date, y = temperature)) + geom_point(aes(color = temp_type)) + facet_wrap(~city_name) + labs(title = "Temperature over Time, Sorted by City", color = "Temperature Type") + xlab("Date") + ylab("Temperature")

```


### part b)
```{r part 3b}
plot_rainfall <- function(city_name, year) {
  if (city_name %in% df$city_name == FALSE) {
    stop("Invalid City!")
  }
  
  if (year %in% df$year == FALSE) {
    stop("Invalid Year!")
  }
  
  plot_title <- paste("Rainfall in", str_to_title(city_name), "During the Year", year, sep = " ")
  
  df %>%
    filter(city_name == city_name, year == year) %>%
    ggplot(aes(log(rainfall))) +
    geom_histogram(bins = 40) + xlab("Log of Rainfall") + ylab("Count of Places/Times with Rainfall") + labs(title = plot_title)
}

plot_rainfall("PERTH", 2000)

```

Function Design: First, I check to see if the city and year are valid. If not, I throw an error.



